---
version: '3.4'
services:
  netbox:
    build:
      dockerfile: Dockerfile-plugin_dev
      context: .
    ports:
      - "8000:8080"
    volumes:
      - ../:/opt/netbox/netbox/netbox-sd-access
      - ~/.gitconfig:/home/ubuntu/.gitconfig:z,ro
      - ~/.ssh:/home/ubuntu/.ssh
